/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarchMadness;
    import javax.swing.*;
    import java.awt.event.*;
    import java.awt.event.ActionListener;

/**
 *
 * @author 1029983
 */
public class BracketExample extends javax.swing.JFrame {

    /**
     * Creates new form BracketExample
     */
    public BracketExample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        southBox1 = new javax.swing.JComboBox<>();
        southBox4 = new javax.swing.JComboBox<>();
        southBox2 = new javax.swing.JComboBox<>();
        southBox3 = new javax.swing.JComboBox<>();
        southBox6 = new javax.swing.JComboBox<>();
        southBox5 = new javax.swing.JComboBox<>();
        southBox7 = new javax.swing.JComboBox<>();
        southBox8 = new javax.swing.JComboBox<>();
        westBox6 = new javax.swing.JComboBox<>();
        westBox7 = new javax.swing.JComboBox<>();
        westBox1 = new javax.swing.JComboBox<>();
        westBox8 = new javax.swing.JComboBox<>();
        westBox2 = new javax.swing.JComboBox<>();
        westBox3 = new javax.swing.JComboBox<>();
        westBox4 = new javax.swing.JComboBox<>();
        westBox5 = new javax.swing.JComboBox<>();
        eastBox1 = new javax.swing.JComboBox<>();
        eastBox4 = new javax.swing.JComboBox<>();
        eastBox2 = new javax.swing.JComboBox<>();
        eastBox3 = new javax.swing.JComboBox<>();
        eastBox6 = new javax.swing.JComboBox<>();
        eastBox5 = new javax.swing.JComboBox<>();
        eastBox7 = new javax.swing.JComboBox<>();
        eastBox8 = new javax.swing.JComboBox<>();
        midBox6 = new javax.swing.JComboBox<>();
        midBox7 = new javax.swing.JComboBox<>();
        midBox1 = new javax.swing.JComboBox<>();
        midBox8 = new javax.swing.JComboBox<>();
        midBox2 = new javax.swing.JComboBox<>();
        midBox3 = new javax.swing.JComboBox<>();
        midBox4 = new javax.swing.JComboBox<>();
        midBox5 = new javax.swing.JComboBox<>();
        eastSweet2 = new javax.swing.JComboBox<>();
        midSweet4 = new javax.swing.JComboBox<>();
        eastSweet1 = new javax.swing.JComboBox<>();
        eastSweet3 = new javax.swing.JComboBox<>();
        eastSweet4 = new javax.swing.JComboBox<>();
        midSweet1 = new javax.swing.JComboBox<>();
        midSweet2 = new javax.swing.JComboBox<>();
        midSweet3 = new javax.swing.JComboBox<>();
        southSweet2 = new javax.swing.JComboBox<>();
        westSweet4 = new javax.swing.JComboBox<>();
        southSweet1 = new javax.swing.JComboBox<>();
        westSweet3 = new javax.swing.JComboBox<>();
        southSweet4 = new javax.swing.JComboBox<>();
        westSweet1 = new javax.swing.JComboBox<>();
        westSweet2 = new javax.swing.JComboBox<>();
        westElite2 = new javax.swing.JComboBox<>();
        southSweet3 = new javax.swing.JComboBox<>();
        southElite1 = new javax.swing.JComboBox<>();
        southElite2 = new javax.swing.JComboBox<>();
        westElite1 = new javax.swing.JComboBox<>();
        midElite1 = new javax.swing.JComboBox<>();
        midElite2 = new javax.swing.JComboBox<>();
        eastElite1 = new javax.swing.JComboBox<>();
        midFinal = new javax.swing.JComboBox<>();
        eastElite2 = new javax.swing.JComboBox<>();
        westFinal = new javax.swing.JComboBox<>();
        eastFinal = new javax.swing.JComboBox<>();
        southFinal = new javax.swing.JComboBox<>();
        finalFour2 = new javax.swing.JComboBox<>();
        finalFour1 = new javax.swing.JComboBox<>();
        finalBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        southBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 SeedS", "16 SeedS" }));
        getContentPane().add(southBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 50, 80, 28));

        southBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 SeedS", "13 SeedS" }));
        getContentPane().add(southBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 170, 80, 28));

        southBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 SeedS", "9 SeedS" }));
        getContentPane().add(southBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 80, 28));

        southBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 SeedS", "12 SeedS" }));
        getContentPane().add(southBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, 80, 28));

        southBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 SeedS", "11 SeedS" }));
        getContentPane().add(southBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 250, 80, 28));

        southBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 SeedS", "14 SeedS" }));
        getContentPane().add(southBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 210, 80, 28));

        southBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 SeedS", "10 SeedS" }));
        getContentPane().add(southBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 290, 80, 28));

        southBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 SeedS", "15 SeedS" }));
        getContentPane().add(southBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 330, 80, 28));

        westBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 SeedW", "11 SeedW" }));
        westBox6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox6PropertyChange(evt);
            }
        });
        getContentPane().add(westBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 620, 80, 28));

        westBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 SeedW", "10 SeedW" }));
        westBox7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox7PropertyChange(evt);
            }
        });
        getContentPane().add(westBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 660, 80, 28));

        westBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 SeedW", "16 SeedW" }));
        westBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox1PropertyChange(evt);
            }
        });
        getContentPane().add(westBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 420, 80, 28));

        westBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 SeedW", "15 SeedW" }));
        westBox8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox8PropertyChange(evt);
            }
        });
        getContentPane().add(westBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 700, 80, 28));

        westBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 SeedW", "9 SeedW" }));
        westBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox2PropertyChange(evt);
            }
        });
        getContentPane().add(westBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 460, 80, 28));

        westBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 SeedW", "12 SeedW" }));
        westBox3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox3PropertyChange(evt);
            }
        });
        getContentPane().add(westBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 500, 80, 28));

        westBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 SeedW", "13 SeedW" }));
        westBox4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox4PropertyChange(evt);
            }
        });
        getContentPane().add(westBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 540, 80, 28));

        westBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 SeedW", "14 SeedW" }));
        westBox5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westBox5PropertyChange(evt);
            }
        });
        getContentPane().add(westBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 580, 80, 28));

        eastBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 SeedE", "16 SeedE" }));
        eastBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 80, 28));

        eastBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 SeedE", "13 SeedE" }));
        eastBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 80, 28));

        eastBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 SeedE", "9 SeedE" }));
        eastBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 80, 28));

        eastBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 SeedE", "12 SeedE" }));
        eastBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 80, 28));

        eastBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 SeedE", "11 SeedE" }));
        eastBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 80, 28));

        eastBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 SeedE", "14 SeedE" }));
        eastBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 80, 28));

        eastBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 SeedE", "10 SeedE" }));
        eastBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 80, 28));

        eastBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 SeedE", "15 SeedE" }));
        eastBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 80, 28));

        midBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 SeedM", "11 SeedM" }));
        midBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 80, 28));

        midBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 SeedM", "10 SeedM" }));
        midBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 80, 28));

        midBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 SeedM", "16SeedM" }));
        midBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 80, 28));

        midBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 SeedM", "15 SeedM" }));
        midBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 80, 28));

        midBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 SeedM", "9 Seed M" }));
        midBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 80, 28));

        midBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 SeedM", "12 SeedM" }));
        midBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 80, 28));

        midBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 SeedM", "13 SeedM" }));
        midBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 80, 28));

        midBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 SeedM", "14 SeedM" }));
        midBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 80, 28));

        eastSweet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastSweet2ActionPerformed(evt);
            }
        });
        getContentPane().add(eastSweet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 80, 28));

        midSweet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midSweet4ActionPerformed(evt);
            }
        });
        getContentPane().add(midSweet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 80, 28));

        eastSweet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastSweet1ActionPerformed(evt);
            }
        });
        getContentPane().add(eastSweet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 80, 28));

        eastSweet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastSweet3ActionPerformed(evt);
            }
        });
        getContentPane().add(eastSweet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 80, 28));

        eastSweet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastSweet4ActionPerformed(evt);
            }
        });
        getContentPane().add(eastSweet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 80, 28));

        midSweet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midSweet1ActionPerformed(evt);
            }
        });
        getContentPane().add(midSweet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 80, 28));

        midSweet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midSweet2ActionPerformed(evt);
            }
        });
        getContentPane().add(midSweet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 80, 28));

        midSweet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midSweet3ActionPerformed(evt);
            }
        });
        getContentPane().add(midSweet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 80, 28));

        getContentPane().add(southSweet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 150, 80, 28));
        southSweet2.getAccessibleContext().setAccessibleName("");

        westSweet4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westSweet4PropertyChange(evt);
            }
        });
        getContentPane().add(westSweet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 680, 80, 28));
        westSweet4.getAccessibleContext().setAccessibleName("");

        getContentPane().add(southSweet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 70, 80, 28));
        southSweet1.getAccessibleContext().setAccessibleName("");

        westSweet3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westSweet3PropertyChange(evt);
            }
        });
        getContentPane().add(westSweet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 610, 80, 28));

        getContentPane().add(southSweet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 300, 80, 28));
        southSweet4.getAccessibleContext().setAccessibleName("");

        westSweet1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westSweet1PropertyChange(evt);
            }
        });
        getContentPane().add(westSweet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 440, 80, 28));
        westSweet1.getAccessibleContext().setAccessibleName("");

        westSweet2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westSweet2PropertyChange(evt);
            }
        });
        getContentPane().add(westSweet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 520, 80, 28));
        westSweet2.getAccessibleContext().setAccessibleName("");

        westElite2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westElite2PropertyChange(evt);
            }
        });
        getContentPane().add(westElite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 80, 28));
        westElite2.getAccessibleContext().setAccessibleName("");

        getContentPane().add(southSweet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 230, 80, 28));
        southSweet3.getAccessibleContext().setAccessibleName("");

        getContentPane().add(southElite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 110, 80, 28));

        getContentPane().add(southElite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 270, 80, 28));

        westElite1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westElite1PropertyChange(evt);
            }
        });
        getContentPane().add(westElite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 480, 80, 28));

        midElite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midElite1ActionPerformed(evt);
            }
        });
        getContentPane().add(midElite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 80, 28));

        midElite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midElite2ActionPerformed(evt);
            }
        });
        getContentPane().add(midElite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 80, 28));

        eastElite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastElite1ActionPerformed(evt);
            }
        });
        getContentPane().add(eastElite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 80, 28));

        midFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midFinalActionPerformed(evt);
            }
        });
        getContentPane().add(midFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 80, 28));

        eastElite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastElite2ActionPerformed(evt);
            }
        });
        getContentPane().add(eastElite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 80, 28));

        westFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                westFinalPropertyChange(evt);
            }
        });
        getContentPane().add(westFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 80, 28));

        eastFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastFinalActionPerformed(evt);
            }
        });
        getContentPane().add(eastFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, 28));

        getContentPane().add(southFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 80, 28));

        finalFour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalFour2ActionPerformed(evt);
            }
        });
        getContentPane().add(finalFour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 80, 28));

        getContentPane().add(finalFour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 80, 28));

        getContentPane().add(finalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void westBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox1PropertyChange
        // TODO add your handling code here:
        String winner = westBox1.getSelectedItem().toString();
        westSweet1.addItem(winner);
    }//GEN-LAST:event_westBox1PropertyChange

    private void westBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox2PropertyChange
        // TODO add your handling code here:
        String winner = westBox2.getSelectedItem().toString();
        westSweet1.addItem(winner);
    }//GEN-LAST:event_westBox2PropertyChange

    private void westBox3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox3PropertyChange
        // TODO add your handling code here:
        String winner = westBox3.getSelectedItem().toString();
        westSweet2.addItem(winner);
    }//GEN-LAST:event_westBox3PropertyChange

    private void westBox4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox4PropertyChange
        // TODO add your handling code here:
        String winner = westBox4.getSelectedItem().toString();
        westSweet2.addItem(winner);
    }//GEN-LAST:event_westBox4PropertyChange

    private void westBox5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox5PropertyChange
        // TODO add your handling code here:
        String winner = westBox5.getSelectedItem().toString();
        westSweet3.addItem(winner);
    }//GEN-LAST:event_westBox5PropertyChange

    private void westBox6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox6PropertyChange
        // TODO add your handling code here:
        String winner = westBox6.getSelectedItem().toString();
        westSweet3.addItem(winner);
    }//GEN-LAST:event_westBox6PropertyChange

    private void westBox7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox7PropertyChange
        // TODO add your handling code here:
        String winner = westBox7.getSelectedItem().toString();
        westSweet4.addItem(winner);
    }//GEN-LAST:event_westBox7PropertyChange

    private void westBox8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westBox8PropertyChange
        // TODO add your handling code here:
        String winner = westBox8.getSelectedItem().toString();
        westSweet4.addItem(winner);
    }//GEN-LAST:event_westBox8PropertyChange

    private void westSweet1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westSweet1PropertyChange
        // TODO add your handling code here:
        String winner = westSweet1.getSelectedItem().toString();
        westElite1.addItem(winner);
    }//GEN-LAST:event_westSweet1PropertyChange

    private void westSweet2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westSweet2PropertyChange
        // TODO add your handling code here:
        String winner = westSweet2.getSelectedItem().toString();
        westElite1.addItem(winner);
    }//GEN-LAST:event_westSweet2PropertyChange

    private void westSweet3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westSweet3PropertyChange
        // TODO add your handling code here:
        String winner = westSweet3.getSelectedItem().toString();
        westElite2.addItem(winner);
    }//GEN-LAST:event_westSweet3PropertyChange

    private void westSweet4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westSweet4PropertyChange
        // TODO add your handling code here:
        String winner = westSweet4.getSelectedItem().toString();
        westElite2.addItem(winner);
    }//GEN-LAST:event_westSweet4PropertyChange

    private void westElite1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westElite1PropertyChange
        // TODO add your handling code here:
        String winner = westElite1.getSelectedItem().toString();
        westFinal.addItem(winner);
    }//GEN-LAST:event_westElite1PropertyChange

    private void westElite2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westElite2PropertyChange
        // TODO add your handling code here:
        String winner = westElite2.getSelectedItem().toString();
        westFinal.addItem(winner);
    }//GEN-LAST:event_westElite2PropertyChange

    private void westFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_westFinalPropertyChange
        // TODO add your handling code here:
        String winner = westFinal.getSelectedItem().toString();
        finalFour1.addItem(winner);
    }//GEN-LAST:event_westFinalPropertyChange

    private void eastBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox4ActionPerformed
        eastSweet2.addItem((String)eastBox4.getSelectedItem());
    }//GEN-LAST:event_eastBox4ActionPerformed

    private void eastBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox3ActionPerformed
        eastSweet2.addItem((String)eastBox3.getSelectedItem());
    }//GEN-LAST:event_eastBox3ActionPerformed

    private void eastBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox1ActionPerformed
        eastSweet1.addItem((String)eastBox1.getSelectedItem());
    }//GEN-LAST:event_eastBox1ActionPerformed

    private void eastBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox2ActionPerformed
        eastSweet1.addItem((String)eastBox2.getSelectedItem());
    }//GEN-LAST:event_eastBox2ActionPerformed

    private void eastBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox5ActionPerformed
        eastSweet3.addItem((String)eastBox5.getSelectedItem());
    }//GEN-LAST:event_eastBox5ActionPerformed

    private void eastBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox6ActionPerformed
        eastSweet3.addItem((String)eastBox6.getSelectedItem());
    }//GEN-LAST:event_eastBox6ActionPerformed

    private void eastBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox7ActionPerformed
        eastSweet4.addItem((String)eastBox7.getSelectedItem());
    }//GEN-LAST:event_eastBox7ActionPerformed

    private void eastBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox8ActionPerformed
        eastSweet4.addItem((String)eastBox8.getSelectedItem());
    }//GEN-LAST:event_eastBox8ActionPerformed

    private void eastSweet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastSweet1ActionPerformed
        eastElite1.addItem((String)eastSweet1.getSelectedItem());
    }//GEN-LAST:event_eastSweet1ActionPerformed

    private void eastSweet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastSweet2ActionPerformed
        eastElite1.addItem((String)eastSweet2.getSelectedItem());
    }//GEN-LAST:event_eastSweet2ActionPerformed

    private void eastSweet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastSweet3ActionPerformed
        eastElite2.addItem((String)eastSweet3.getSelectedItem());
    }//GEN-LAST:event_eastSweet3ActionPerformed

    private void eastSweet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastSweet4ActionPerformed
        eastElite2.addItem((String)eastSweet4.getSelectedItem());
    }//GEN-LAST:event_eastSweet4ActionPerformed

    private void eastElite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastElite2ActionPerformed
        eastFinal.addItem((String)eastElite2.getSelectedItem());
    }//GEN-LAST:event_eastElite2ActionPerformed

    private void eastElite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastElite1ActionPerformed
        eastFinal.addItem((String)eastElite1.getSelectedItem());
    }//GEN-LAST:event_eastElite1ActionPerformed

    private void eastFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastFinalActionPerformed
        finalFour2.addItem((String)eastFinal.getSelectedItem());
    }//GEN-LAST:event_eastFinalActionPerformed

    private void finalFour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalFour2ActionPerformed
        finalBox.addItem((String)finalFour2.getSelectedItem());
    }//GEN-LAST:event_finalFour2ActionPerformed

    private void midBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox1ActionPerformed
        eastSweet2.addItem((String)eastBox4.getSelectedItem());
    }//GEN-LAST:event_midBox1ActionPerformed

    private void midBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox2ActionPerformed

    private void midBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox3ActionPerformed

    private void midBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox4ActionPerformed

    private void midBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox5ActionPerformed

    private void midBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox6ActionPerformed

    private void midBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox7ActionPerformed

    private void midBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midBox8ActionPerformed

    private void midSweet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midSweet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midSweet1ActionPerformed

    private void midSweet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midSweet2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midSweet2ActionPerformed

    private void midSweet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midSweet3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midSweet3ActionPerformed

    private void midSweet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midSweet4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midSweet4ActionPerformed

    private void midElite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midElite1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midElite1ActionPerformed

    private void midElite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midElite2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midElite2ActionPerformed

    private void midFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BracketExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BracketExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BracketExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BracketExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BracketExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> eastBox1;
    private javax.swing.JComboBox<String> eastBox2;
    private javax.swing.JComboBox<String> eastBox3;
    private javax.swing.JComboBox<String> eastBox4;
    private javax.swing.JComboBox<String> eastBox5;
    private javax.swing.JComboBox<String> eastBox6;
    private javax.swing.JComboBox<String> eastBox7;
    private javax.swing.JComboBox<String> eastBox8;
    private javax.swing.JComboBox<String> eastElite1;
    private javax.swing.JComboBox<String> eastElite2;
    private javax.swing.JComboBox<String> eastFinal;
    private javax.swing.JComboBox<String> eastSweet1;
    private javax.swing.JComboBox<String> eastSweet2;
    private javax.swing.JComboBox<String> eastSweet3;
    private javax.swing.JComboBox<String> eastSweet4;
    private javax.swing.JComboBox<String> finalBox;
    private javax.swing.JComboBox<String> finalFour1;
    private javax.swing.JComboBox<String> finalFour2;
    private javax.swing.JComboBox<String> midBox1;
    private javax.swing.JComboBox<String> midBox2;
    private javax.swing.JComboBox<String> midBox3;
    private javax.swing.JComboBox<String> midBox4;
    private javax.swing.JComboBox<String> midBox5;
    private javax.swing.JComboBox<String> midBox6;
    private javax.swing.JComboBox<String> midBox7;
    private javax.swing.JComboBox<String> midBox8;
    private javax.swing.JComboBox<String> midElite1;
    private javax.swing.JComboBox<String> midElite2;
    private javax.swing.JComboBox<String> midFinal;
    private javax.swing.JComboBox<String> midSweet1;
    private javax.swing.JComboBox<String> midSweet2;
    private javax.swing.JComboBox<String> midSweet3;
    private javax.swing.JComboBox<String> midSweet4;
    private javax.swing.JComboBox<String> southBox1;
    private javax.swing.JComboBox<String> southBox2;
    private javax.swing.JComboBox<String> southBox3;
    private javax.swing.JComboBox<String> southBox4;
    private javax.swing.JComboBox<String> southBox5;
    private javax.swing.JComboBox<String> southBox6;
    private javax.swing.JComboBox<String> southBox7;
    private javax.swing.JComboBox<String> southBox8;
    private javax.swing.JComboBox<String> southElite1;
    private javax.swing.JComboBox<String> southElite2;
    private javax.swing.JComboBox<String> southFinal;
    private javax.swing.JComboBox<String> southSweet1;
    private javax.swing.JComboBox<String> southSweet2;
    private javax.swing.JComboBox<String> southSweet3;
    private javax.swing.JComboBox<String> southSweet4;
    private javax.swing.JComboBox<String> westBox1;
    private javax.swing.JComboBox<String> westBox2;
    private javax.swing.JComboBox<String> westBox3;
    private javax.swing.JComboBox<String> westBox4;
    private javax.swing.JComboBox<String> westBox5;
    private javax.swing.JComboBox<String> westBox6;
    private javax.swing.JComboBox<String> westBox7;
    private javax.swing.JComboBox<String> westBox8;
    private javax.swing.JComboBox<String> westElite1;
    private javax.swing.JComboBox<String> westElite2;
    private javax.swing.JComboBox<String> westFinal;
    private javax.swing.JComboBox<String> westSweet1;
    private javax.swing.JComboBox<String> westSweet2;
    private javax.swing.JComboBox<String> westSweet3;
    private javax.swing.JComboBox<String> westSweet4;
    // End of variables declaration//GEN-END:variables
}
