/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarchMadness;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1029983
 */
public class MasterBracket extends javax.swing.JFrame {

    /**
     * Creates new form MasterBracket
     */
    
    public String[] south32Winners = new String[8];                                // arrays for the round winners per each quadrent
    public String[] west32Winners = new String[8];
    public String[] east32Winners = new String[8];
    public String[] mid32Winners = new String[8];
        
    public String[] southSweet = new String[4];
    public String[] westSweet = new String[4];
    public String[] eastSweet = new String[4];
    public String[] midSweet = new String[4];
        
    public String[] southElite = new String[2];
    public String[] westElite = new String[2];
    public String[] eastElite = new String[2];
    public String[] midElite = new String[2];
        
    public String southFinal = "";                                                 // String variables for Final Four and beyond
    public String westFinal = "";
    public String eastFinal = "";
    public String midFinal = "";
    public String leftFinalTeam = "";
    public String rightFinalTeam = "";
    public String champion = "";
        
    public MasterBracket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        southBox1 = new javax.swing.JComboBox<>();
        southBox4 = new javax.swing.JComboBox<>();
        southBox2 = new javax.swing.JComboBox<>();
        southBox3 = new javax.swing.JComboBox<>();
        southBox6 = new javax.swing.JComboBox<>();
        southBox5 = new javax.swing.JComboBox<>();
        southBox7 = new javax.swing.JComboBox<>();
        southBox8 = new javax.swing.JComboBox<>();
        westBox6 = new javax.swing.JComboBox<>();
        westBox7 = new javax.swing.JComboBox<>();
        westBox1 = new javax.swing.JComboBox<>();
        westBox8 = new javax.swing.JComboBox<>();
        westBox2 = new javax.swing.JComboBox<>();
        westBox3 = new javax.swing.JComboBox<>();
        westBox4 = new javax.swing.JComboBox<>();
        westBox5 = new javax.swing.JComboBox<>();
        eastBox1 = new javax.swing.JComboBox<>();
        eastBox4 = new javax.swing.JComboBox<>();
        eastBox2 = new javax.swing.JComboBox<>();
        eastBox3 = new javax.swing.JComboBox<>();
        eastBox6 = new javax.swing.JComboBox<>();
        eastBox5 = new javax.swing.JComboBox<>();
        eastBox7 = new javax.swing.JComboBox<>();
        eastBox8 = new javax.swing.JComboBox<>();
        midBox6 = new javax.swing.JComboBox<>();
        midBox7 = new javax.swing.JComboBox<>();
        midBox1 = new javax.swing.JComboBox<>();
        midBox8 = new javax.swing.JComboBox<>();
        midBox2 = new javax.swing.JComboBox<>();
        midBox3 = new javax.swing.JComboBox<>();
        midBox4 = new javax.swing.JComboBox<>();
        midBox5 = new javax.swing.JComboBox<>();
        nameField = new javax.swing.JTextField();
        southSweetField1 = new javax.swing.JTextField();
        southSweetField2 = new javax.swing.JTextField();
        southSweetField3 = new javax.swing.JTextField();
        southSweetField4 = new javax.swing.JTextField();
        westSweetField1 = new javax.swing.JTextField();
        westSweetField2 = new javax.swing.JTextField();
        westSweetField3 = new javax.swing.JTextField();
        westSweetField4 = new javax.swing.JTextField();
        eastSweetField1 = new javax.swing.JTextField();
        eastSweetField2 = new javax.swing.JTextField();
        eastSweetField3 = new javax.swing.JTextField();
        eastSweetField4 = new javax.swing.JTextField();
        midSweetField1 = new javax.swing.JTextField();
        midSweetField2 = new javax.swing.JTextField();
        midSweetField3 = new javax.swing.JTextField();
        midSweetField4 = new javax.swing.JTextField();
        southEliteField1 = new javax.swing.JTextField();
        southEliteField2 = new javax.swing.JTextField();
        westEliteField1 = new javax.swing.JTextField();
        westEliteField2 = new javax.swing.JTextField();
        eastEliteField1 = new javax.swing.JTextField();
        eastEliteField2 = new javax.swing.JTextField();
        midEliteField1 = new javax.swing.JTextField();
        midEliteField2 = new javax.swing.JTextField();
        southFinal4Field = new javax.swing.JTextField();
        westFinal4Field = new javax.swing.JTextField();
        eastFinal4Field = new javax.swing.JTextField();
        midFinal4Field = new javax.swing.JTextField();
        leftFinalField = new javax.swing.JTextField();
        rightFinalField = new javax.swing.JTextField();
        championField = new javax.swing.JTextField();
        lockButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        southBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 50, 80, 28));

        southBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 170, 80, 28));

        southBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 80, 28));

        southBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, 80, 28));

        southBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 250, 80, 28));

        southBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 210, 80, 28));

        southBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 290, 80, 28));

        southBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(southBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 330, 80, 28));

        westBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 620, 80, 28));

        westBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 660, 80, 28));

        westBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 420, 80, 28));

        westBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 700, 80, 28));

        westBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 460, 80, 28));

        westBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 500, 80, 28));

        westBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 540, 80, 28));

        westBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(westBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 580, 80, 28));

        eastBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 80, 28));

        eastBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 80, 28));

        eastBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 80, 28));

        eastBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 80, 28));

        eastBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 80, 28));

        eastBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 80, 28));

        eastBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 80, 28));

        eastBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(eastBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 80, 28));

        midBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 80, 28));

        midBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 80, 28));

        midBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 80, 28));

        midBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 80, 28));

        midBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 80, 28));

        midBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 80, 28));

        midBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 80, 28));

        midBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(midBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 80, 28));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setText("Main Bracket");
        nameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 160, 40));
        getContentPane().add(southSweetField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 70, 80, 28));
        getContentPane().add(southSweetField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 150, 80, 28));
        getContentPane().add(southSweetField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 230, 80, 28));
        getContentPane().add(southSweetField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 310, 80, 28));
        getContentPane().add(westSweetField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 440, 80, 28));
        getContentPane().add(westSweetField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 520, 80, 28));
        getContentPane().add(westSweetField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 600, 80, 28));
        getContentPane().add(westSweetField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 680, 80, 28));
        getContentPane().add(eastSweetField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 80, 28));
        getContentPane().add(eastSweetField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 80, 28));
        getContentPane().add(eastSweetField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 80, 28));
        getContentPane().add(eastSweetField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 80, 28));
        getContentPane().add(midSweetField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 80, 28));
        getContentPane().add(midSweetField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 80, 28));
        getContentPane().add(midSweetField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 80, 28));
        getContentPane().add(midSweetField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 80, 28));
        getContentPane().add(southEliteField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 110, 80, 28));
        getContentPane().add(southEliteField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 270, 80, 28));
        getContentPane().add(westEliteField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 480, 80, 28));
        getContentPane().add(westEliteField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 640, 80, 28));
        getContentPane().add(eastEliteField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 80, 28));
        getContentPane().add(eastEliteField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 80, 28));
        getContentPane().add(midEliteField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 80, 28));
        getContentPane().add(midEliteField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 80, 28));
        getContentPane().add(southFinal4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 80, 28));
        getContentPane().add(westFinal4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 80, 28));
        getContentPane().add(eastFinal4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, 28));
        getContentPane().add(midFinal4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 80, 28));
        getContentPane().add(leftFinalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 80, 28));
        getContentPane().add(rightFinalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 80, 28));
        getContentPane().add(championField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 90, 40));

        lockButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lockButton.setText("Lock");
        lockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 100, 50));

        menuButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuButton.setText("Exit");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 690, 100, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("South");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 195, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MidWest");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 565, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("East");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 195, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("West");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 565, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eastBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox4ActionPerformed
//            eastSweet2.addItem((String)eastBox4.getSelectedItem());             // chooses the selected pick in eastBox1, converts the int value to
//                                                                                // a string, and then adds the string to the eastSweet1 combobox
                                                                                // code to make a true bracket with comboBoxes
    }//GEN-LAST:event_eastBox4ActionPerformed

    private void eastBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox3ActionPerformed
//        eastSweet2.addItem((String)eastBox3.getSelectedItem());
    }//GEN-LAST:event_eastBox3ActionPerformed

    private void eastBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox1ActionPerformed
//        eastSweet1.addItem((String)eastBox1.getSelectedItem());
    }//GEN-LAST:event_eastBox1ActionPerformed

    private void eastBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox2ActionPerformed
//        eastSweet1.addItem((String)eastBox2.getSelectedItem());
    }//GEN-LAST:event_eastBox2ActionPerformed

    private void eastBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox5ActionPerformed
//        eastSweet3.addItem((String)eastBox5.getSelectedItem());
    }//GEN-LAST:event_eastBox5ActionPerformed

    private void eastBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox6ActionPerformed
//        eastSweet3.addItem((String)eastBox6.getSelectedItem());
    }//GEN-LAST:event_eastBox6ActionPerformed

    private void eastBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox7ActionPerformed
//        eastSweet4.addItem((String)eastBox7.getSelectedItem());
    }//GEN-LAST:event_eastBox7ActionPerformed

    private void eastBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastBox8ActionPerformed
//        eastSweet4.addItem((String)eastBox8.getSelectedItem());
    }//GEN-LAST:event_eastBox8ActionPerformed

    private void midBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox1ActionPerformed
//        midSweet1.addItem((String)midBox1.getSelectedItem());
    }//GEN-LAST:event_midBox1ActionPerformed

    private void midBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox2ActionPerformed
//        midSweet1.addItem((String)midBox2.getSelectedItem());
    }//GEN-LAST:event_midBox2ActionPerformed

    private void midBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox3ActionPerformed
//        midSweet2.addItem((String)midBox3.getSelectedItem());
    }//GEN-LAST:event_midBox3ActionPerformed

    private void midBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox4ActionPerformed
//        midSweet2.addItem((String)midBox4.getSelectedItem());
    }//GEN-LAST:event_midBox4ActionPerformed

    private void midBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox5ActionPerformed
//        midSweet3.addItem((String)midBox5.getSelectedItem());
    }//GEN-LAST:event_midBox5ActionPerformed

    private void midBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox6ActionPerformed
//        midSweet3.addItem((String)midBox6.getSelectedItem());
    }//GEN-LAST:event_midBox6ActionPerformed

    private void midBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox7ActionPerformed
//        midSweet4.addItem((String)midBox7.getSelectedItem());
    }//GEN-LAST:event_midBox7ActionPerformed

    private void midBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midBox8ActionPerformed
//        midSweet4.addItem((String)midBox8.getSelectedItem());
    }//GEN-LAST:event_midBox8ActionPerformed

    private void westBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox1ActionPerformed
//        westSweet1.addItem((String)westBox1.getSelectedItem());
    }//GEN-LAST:event_westBox1ActionPerformed

    private void westBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox2ActionPerformed
//        westSweet1.addItem((String)westBox2.getSelectedItem());
    }//GEN-LAST:event_westBox2ActionPerformed

    private void westBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox3ActionPerformed
//        westSweet2.addItem((String)westBox3.getSelectedItem());;
    }//GEN-LAST:event_westBox3ActionPerformed

    private void westBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox4ActionPerformed
//        westSweet2.addItem((String)westBox4.getSelectedItem());
    }//GEN-LAST:event_westBox4ActionPerformed

    private void westBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox5ActionPerformed
//        westSweet3.addItem((String)westBox5.getSelectedItem());
    }//GEN-LAST:event_westBox5ActionPerformed

    private void westBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox6ActionPerformed
//        westSweet3.addItem((String)westBox6.getSelectedItem());
    }//GEN-LAST:event_westBox6ActionPerformed

    private void westBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox7ActionPerformed
//        westSweet4.addItem((String)westBox7.getSelectedItem());
    }//GEN-LAST:event_westBox7ActionPerformed

    private void westBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westBox8ActionPerformed
//        westSweet4.addItem((String)westBox8.getSelectedItem());
    }//GEN-LAST:event_westBox8ActionPerformed

    private void southBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox1ActionPerformed
//        southSweet1.addItem((String)southBox1.getSelectedItem());
    }//GEN-LAST:event_southBox1ActionPerformed

    private void southBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox2ActionPerformed
//        southSweet1.addItem((String)southBox2.getSelectedItem());
    }//GEN-LAST:event_southBox2ActionPerformed

    private void southBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox3ActionPerformed
//        southSweet2.addItem((String)southBox3.getSelectedItem());
    }//GEN-LAST:event_southBox3ActionPerformed

    private void southBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox4ActionPerformed
//        southSweet2.addItem((String)southBox4.getSelectedItem());
    }//GEN-LAST:event_southBox4ActionPerformed

    private void southBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox5ActionPerformed
//        southSweet3.addItem((String)southBox5.getSelectedItem());
    }//GEN-LAST:event_southBox5ActionPerformed

    private void southBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox6ActionPerformed
//        southSweet3.addItem((String)southBox6.getSelectedItem());
    }//GEN-LAST:event_southBox6ActionPerformed

    private void southBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox7ActionPerformed
//        southSweet4.addItem((String)southBox7.getSelectedItem());
    }//GEN-LAST:event_southBox7ActionPerformed

    private void southBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southBox8ActionPerformed
//        southSweet4.addItem((String)southBox8.getSelectedItem());
    }//GEN-LAST:event_southBox8ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        MasterBracket.this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void getRound32Winners()
    {
        south32Winners[0] = (String)southBox1.getSelectedItem();
        south32Winners[1] = (String)southBox2.getSelectedItem();
        south32Winners[2] = (String)southBox3.getSelectedItem();
        south32Winners[3] = (String)southBox4.getSelectedItem();
        south32Winners[4] = (String)southBox5.getSelectedItem();
        south32Winners[5] = (String)southBox6.getSelectedItem();
        south32Winners[6] = (String)southBox7.getSelectedItem();
        south32Winners[7] = (String)southBox8.getSelectedItem();
        west32Winners[0] = (String)westBox1.getSelectedItem();
        west32Winners[1] = (String)westBox2.getSelectedItem();
        west32Winners[2] = (String)westBox3.getSelectedItem();
        west32Winners[3] = (String)westBox4.getSelectedItem();
        west32Winners[4] = (String)westBox5.getSelectedItem();
        west32Winners[5] = (String)westBox6.getSelectedItem();
        west32Winners[6] = (String)westBox7.getSelectedItem();
        west32Winners[7] = (String)westBox7.getSelectedItem();
        east32Winners[0] = (String)eastBox1.getSelectedItem();
        east32Winners[1] = (String)eastBox2.getSelectedItem();
        east32Winners[2] = (String)eastBox3.getSelectedItem();
        east32Winners[3] = (String)eastBox4.getSelectedItem();
        east32Winners[4] = (String)eastBox5.getSelectedItem();
        east32Winners[5] = (String)eastBox6.getSelectedItem();
        east32Winners[6] = (String)eastBox7.getSelectedItem();
        east32Winners[7] = (String)eastBox8.getSelectedItem();
        mid32Winners[0] = (String)midBox1.getSelectedItem();
        mid32Winners[1] = (String)midBox2.getSelectedItem();
        mid32Winners[2] = (String)midBox3.getSelectedItem();
        mid32Winners[3] = (String)midBox4.getSelectedItem();
        mid32Winners[4] = (String)midBox5.getSelectedItem();
        mid32Winners[5] = (String)midBox6.getSelectedItem();
        mid32Winners[6] = (String)midBox7.getSelectedItem();
        mid32Winners[7] = (String)midBox8.getSelectedItem();
    }
    
    private void saveRound32Winners() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("Round32Winners.txt"));
        
        for (int i = 0; i < south32Winners.length; i++)
        {
            writer.println(south32Winners[i]);
        }
        for (int i = 0; i < west32Winners.length; i++)
        {
            writer.println(west32Winners[i]);
        }
        for (int i = 0; i < east32Winners.length; i++)
        {
            writer.println(east32Winners[i]);
        }
        for (int i = 0; i < mid32Winners.length; i++)
        {
            writer.println(mid32Winners[i]);
        }
        writer.flush();
        writer.close();
    }
    
    private void getSweetSixteen()
    {
        southSweet[0] = southSweetField1.getText();
        southSweet[1] = southSweetField2.getText();
        southSweet[2] = southSweetField3.getText();
        southSweet[3] = southSweetField4.getText();
        westSweet[0] = westSweetField1.getText();
        westSweet[1] = westSweetField2.getText();
        westSweet[2] = westSweetField3.getText();
        westSweet[3] = westSweetField4.getText();
        eastSweet[0] = eastSweetField1.getText();
        eastSweet[1] = eastSweetField2.getText();
        eastSweet[2] = eastSweetField3.getText();
        eastSweet[3] = eastSweetField4.getText();
        midSweet[0] = midSweetField1.getText();
        midSweet[1] = midSweetField2.getText();
        midSweet[2] = midSweetField3.getText();
        midSweet[3] = midSweetField4.getText();
    }
    
    private void saveSweetSixteen() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("SweetSixteen.txt"));
        
        for (int i = 0; i < southSweet.length; i++)
        {
            writer.println(southSweet[i]);
        }
        for (int i = 0; i < westSweet.length; i++)
        {
            writer.println(westSweet[i]);
        }
        for (int i = 0; i < eastSweet.length; i++)
        {
            writer.println(eastSweet[i]);
        }
        for (int i = 0; i < midSweet.length; i++)
        {
            writer.println(midSweet[i]);
        }
        writer.flush();
        writer.close();
    }
    
    private void getEliteEight()
    {
        southElite[0] = southEliteField1.getText();
        southElite[1] = southEliteField2.getText();
        southElite[0] = westEliteField1.getText();
        westElite[1] = westEliteField2.getText();
        eastElite[0] = eastEliteField1.getText();
        eastElite[1] = eastEliteField2.getText();
        midElite[0] = midEliteField1.getText();
        midElite[1] = midEliteField2.getText();
        
    }
    
    private void saveEliteEight() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("EliteEight.txt"));
        
        for (int i = 0; i < southElite.length; i++)
        {
            writer.println(southElite[i]);
        }
        for (int i = 0; i < westElite.length; i++)
        {
            writer.println(westElite[i]);
        }
        for (int i = 0; i < eastElite.length; i++)
        {
            writer.println(eastElite[i]);
        }
        for (int i = 0; i < midElite.length; i++)
        {
            writer.println(midElite[i]);
        }
        writer.flush();
        writer.close();
    }
    
    private void getFinalFour()
    {
        southFinal = southFinal4Field.getText();
        eastFinal = eastFinal4Field.getText();
        westFinal = westFinal4Field.getText();
        midFinal = midFinal4Field.getText();
    }
    
    private void saveFinalFour() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("FinalFour.txt"));
        
        writer.println(southFinal);
        writer.println(eastFinal);
        writer.println(westFinal);
        writer.println(midFinal);
        writer.flush();
        writer.close();
    }
    
    private void getFinalTwo()
    {
        leftFinalTeam = leftFinalField.getText();
        rightFinalTeam = rightFinalField.getText();
    }
    
    private void saveFinalTwo() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("FinalTwo.txt"));
        
        writer.println(leftFinalTeam);
        writer.println(rightFinalTeam);
        writer.flush();
        writer.close();
    }
    
    private void getChampion()
    {
        champion = championField.getText();
    }
    
    private void saveChampion() throws FileNotFoundException
    {
        PrintWriter writer = new PrintWriter(new File("Champion.txt"));
        
        writer.println(champion);
        writer.flush();
        writer.close();
    }
    
    private void lockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockButtonActionPerformed
        try {
            TeamManager manager = new TeamManager();
        }
        catch (IOException ex) {
            Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (southSweetField1.getText().equals(""))
        {
            getRound32Winners();
            try {
                saveRound32Winners();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (southEliteField1.getText().equals(""))
        {
            getSweetSixteen();
            try {
                saveSweetSixteen();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (southFinal4Field.getText().equals(""))
        {
            getEliteEight();
            try {
                saveEliteEight();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (leftFinalField.getText().equals(""))
        {
            getFinalFour();
            try {
                saveFinalFour();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (championField.getText().equals(""))
        {
            getFinalTwo();
            try {
                saveFinalTwo();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (!championField.getText().equals(""))
        {
            getChampion();
            try {
                saveChampion();
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(MasterBracket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            System.out.println("Error, nothing more can be locked!");
        }

    }//GEN-LAST:event_lockButtonActionPerformed

    public void setComboBoxes() throws IOException                              // sets all the combo boxes with team names from TeamManager
    {
        TeamManager manager = new TeamManager();
        
        System.out.println("monkey");
        System.out.println(manager.teams[0].getTeamName());
        
        Scanner round = new Scanner(new File("Round32Winners.txt"));
        
        if (!round.hasNextLine())
        {
            southBox1.addItem(manager.teams[0].getTeamName());
            southBox1.addItem(manager.teams[15].getTeamName());
            southBox2.addItem(manager.teams[7].getTeamName());
            southBox2.addItem(manager.teams[8].getTeamName());
            southBox3.addItem(manager.teams[4].getTeamName());
            southBox3.addItem(manager.teams[11].getTeamName());
            southBox4.addItem(manager.teams[3].getTeamName());
            southBox4.addItem(manager.teams[12].getTeamName());
            southBox5.addItem(manager.teams[5].getTeamName());
            southBox5.addItem(manager.teams[10].getTeamName());
            southBox6.addItem(manager.teams[2].getTeamName());
            southBox6.addItem(manager.teams[13].getTeamName());
            southBox7.addItem(manager.teams[6].getTeamName());
            southBox7.addItem(manager.teams[9].getTeamName());
            southBox8.addItem(manager.teams[1].getTeamName());
            southBox8.addItem(manager.teams[14].getTeamName());
            westBox1.addItem(manager.teams[16].getTeamName());
            westBox1.addItem(manager.teams[31].getTeamName());
            westBox2.addItem(manager.teams[23].getTeamName());
            westBox2.addItem(manager.teams[24].getTeamName());
            westBox3.addItem(manager.teams[20].getTeamName());
            westBox3.addItem(manager.teams[27].getTeamName());
            westBox4.addItem(manager.teams[19].getTeamName());
            westBox4.addItem(manager.teams[28].getTeamName());
            westBox5.addItem(manager.teams[21].getTeamName());
            westBox5.addItem(manager.teams[26].getTeamName());
            westBox6.addItem(manager.teams[18].getTeamName());
            westBox6.addItem(manager.teams[29].getTeamName());
            westBox7.addItem(manager.teams[22].getTeamName());
            westBox7.addItem(manager.teams[25].getTeamName());
            westBox8.addItem(manager.teams[17].getTeamName());
            westBox8.addItem(manager.teams[30].getTeamName());
            eastBox1.addItem(manager.teams[32].getTeamName());
            eastBox1.addItem(manager.teams[47].getTeamName());
            eastBox2.addItem(manager.teams[39].getTeamName());
            eastBox2.addItem(manager.teams[40].getTeamName());
            eastBox3.addItem(manager.teams[36].getTeamName());
            eastBox3.addItem(manager.teams[43].getTeamName());
            eastBox4.addItem(manager.teams[35].getTeamName());
            eastBox4.addItem(manager.teams[44].getTeamName());
            eastBox5.addItem(manager.teams[37].getTeamName());
            eastBox5.addItem(manager.teams[42].getTeamName());
            eastBox6.addItem(manager.teams[34].getTeamName());
            eastBox6.addItem(manager.teams[45].getTeamName());
            eastBox7.addItem(manager.teams[38].getTeamName());
            eastBox7.addItem(manager.teams[41].getTeamName());
            eastBox8.addItem(manager.teams[33].getTeamName());
            eastBox8.addItem(manager.teams[46].getTeamName());
            midBox1.addItem(manager.teams[48].getTeamName());
            midBox1.addItem(manager.teams[63].getTeamName());
            midBox2.addItem(manager.teams[55].getTeamName());
            midBox2.addItem(manager.teams[56].getTeamName());
            midBox3.addItem(manager.teams[52].getTeamName());
            midBox3.addItem(manager.teams[59].getTeamName());
            midBox4.addItem(manager.teams[51].getTeamName());
            midBox4.addItem(manager.teams[60].getTeamName());
            midBox5.addItem(manager.teams[53].getTeamName());
            midBox5.addItem(manager.teams[58].getTeamName());
            midBox6.addItem(manager.teams[50].getTeamName());
            midBox6.addItem(manager.teams[61].getTeamName());
            midBox7.addItem(manager.teams[54].getTeamName());
            midBox7.addItem(manager.teams[57].getTeamName());
            midBox8.addItem(manager.teams[49].getTeamName());
            midBox8.addItem(manager.teams[62].getTeamName());
        }
    }
    
    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBracket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBracket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField championField;
    private javax.swing.JComboBox<String> eastBox1;
    private javax.swing.JComboBox<String> eastBox2;
    private javax.swing.JComboBox<String> eastBox3;
    private javax.swing.JComboBox<String> eastBox4;
    private javax.swing.JComboBox<String> eastBox5;
    private javax.swing.JComboBox<String> eastBox6;
    private javax.swing.JComboBox<String> eastBox7;
    private javax.swing.JComboBox<String> eastBox8;
    private javax.swing.JTextField eastEliteField1;
    private javax.swing.JTextField eastEliteField2;
    private javax.swing.JTextField eastFinal4Field;
    private javax.swing.JTextField eastSweetField1;
    private javax.swing.JTextField eastSweetField2;
    private javax.swing.JTextField eastSweetField3;
    private javax.swing.JTextField eastSweetField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField leftFinalField;
    private javax.swing.JButton lockButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JComboBox<String> midBox1;
    private javax.swing.JComboBox<String> midBox2;
    private javax.swing.JComboBox<String> midBox3;
    private javax.swing.JComboBox<String> midBox4;
    private javax.swing.JComboBox<String> midBox5;
    private javax.swing.JComboBox<String> midBox6;
    private javax.swing.JComboBox<String> midBox7;
    private javax.swing.JComboBox<String> midBox8;
    private javax.swing.JTextField midEliteField1;
    private javax.swing.JTextField midEliteField2;
    private javax.swing.JTextField midFinal4Field;
    private javax.swing.JTextField midSweetField1;
    private javax.swing.JTextField midSweetField2;
    private javax.swing.JTextField midSweetField3;
    private javax.swing.JTextField midSweetField4;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField rightFinalField;
    private javax.swing.JComboBox<String> southBox1;
    private javax.swing.JComboBox<String> southBox2;
    private javax.swing.JComboBox<String> southBox3;
    private javax.swing.JComboBox<String> southBox4;
    private javax.swing.JComboBox<String> southBox5;
    private javax.swing.JComboBox<String> southBox6;
    private javax.swing.JComboBox<String> southBox7;
    private javax.swing.JComboBox<String> southBox8;
    private javax.swing.JTextField southEliteField1;
    private javax.swing.JTextField southEliteField2;
    private javax.swing.JTextField southFinal4Field;
    private javax.swing.JTextField southSweetField1;
    private javax.swing.JTextField southSweetField2;
    private javax.swing.JTextField southSweetField3;
    private javax.swing.JTextField southSweetField4;
    private javax.swing.JComboBox<String> westBox1;
    private javax.swing.JComboBox<String> westBox2;
    private javax.swing.JComboBox<String> westBox3;
    private javax.swing.JComboBox<String> westBox4;
    private javax.swing.JComboBox<String> westBox5;
    private javax.swing.JComboBox<String> westBox6;
    private javax.swing.JComboBox<String> westBox7;
    private javax.swing.JComboBox<String> westBox8;
    private javax.swing.JTextField westEliteField1;
    private javax.swing.JTextField westEliteField2;
    private javax.swing.JTextField westFinal4Field;
    private javax.swing.JTextField westSweetField1;
    private javax.swing.JTextField westSweetField2;
    private javax.swing.JTextField westSweetField3;
    private javax.swing.JTextField westSweetField4;
    // End of variables declaration//GEN-END:variables

}
