/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarchMadness;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1029983
 */
public class GameResults extends javax.swing.JDialog {

    /**
     * Creates new form GameResults
     */
    public GameResults(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bracketUpsetsButton = new javax.swing.JButton();
        winsBySeedButton = new javax.swing.JButton();
        northSouthButton = new javax.swing.JButton();
        animalHumanoidButton = new javax.swing.JButton();
        sizeTuitionButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        roundHeading = new javax.swing.JTextField();
        round64Button = new javax.swing.JButton();
        round32Button = new javax.swing.JButton();
        sweet16Button = new javax.swing.JButton();
        elite8Button = new javax.swing.JButton();
        final4Button = new javax.swing.JButton();
        finalGameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 780));
        getContentPane().setLayout(null);

        jButton1.setText("Game Results");
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 130, 130);

        bracketUpsetsButton.setText("Bracket Upsets");
        bracketUpsetsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketUpsetsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bracketUpsetsButton);
        bracketUpsetsButton.setBounds(0, 130, 130, 130);

        winsBySeedButton.setText("Wins by Seed");
        winsBySeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winsBySeedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(winsBySeedButton);
        winsBySeedButton.setBounds(0, 260, 130, 130);

        northSouthButton.setText("North v South");
        northSouthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northSouthButtonActionPerformed(evt);
            }
        });
        getContentPane().add(northSouthButton);
        northSouthButton.setBounds(0, 650, 130, 130);

        animalHumanoidButton.setText("Animal v Humanoid");
        animalHumanoidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalHumanoidButtonActionPerformed(evt);
            }
        });
        getContentPane().add(animalHumanoidButton);
        animalHumanoidButton.setBounds(0, 390, 130, 130);

        sizeTuitionButton.setText("Size/Tuition Upsets");
        sizeTuitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTuitionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sizeTuitionButton);
        sizeTuitionButton.setBounds(0, 520, 130, 130);

        exitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(1100, 740, 70, 30);

        roundHeading.setEditable(false);
        roundHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roundHeading.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(roundHeading);
        roundHeading.setBounds(610, 20, 150, 40);

        round64Button.setText("Round of 64");
        round64Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                round64ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(round64Button);
        round64Button.setBounds(175, 180, 100, 30);

        round32Button.setText("Round of 32");
        round32Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                round32ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(round32Button);
        round32Button.setBounds(175, 260, 100, 30);

        sweet16Button.setText("Sweet 16");
        sweet16Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sweet16ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sweet16Button);
        sweet16Button.setBounds(175, 340, 100, 30);

        elite8Button.setText("Elite 8");
        elite8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elite8ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(elite8Button);
        elite8Button.setBounds(175, 420, 100, 30);

        final4Button.setText("Final 4");
        final4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final4ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(final4Button);
        final4Button.setBounds(175, 500, 100, 30);

        finalGameButton.setText("Final Game");
        finalGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(finalGameButton);
        finalGameButton.setBounds(175, 580, 100, 30);

        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textArea1.setRows(5);
        jScrollPane1.setViewportView(textArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 80, 360, 660);

        textArea2.setColumns(20);
        textArea2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textArea2.setRows(5);
        jScrollPane2.setViewportView(textArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(690, 80, 360, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void northSouthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northSouthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_northSouthButtonActionPerformed

    private void sizeTuitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTuitionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeTuitionButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        GameResults.this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void bracketUpsetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracketUpsetsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bracketUpsetsButtonActionPerformed

    private void winsBySeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winsBySeedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_winsBySeedButtonActionPerformed

    private void animalHumanoidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalHumanoidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalHumanoidButtonActionPerformed

    private void round64ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_round64ButtonActionPerformed
        textArea1.setText("");
        textArea1.setText("");
        roundHeading.setText("Round of 64");
        
        try {
            TeamManager manager = new TeamManager();
            manager.teamInformation();
            
            Scanner scan1 = new Scanner(new File("Round64Losers.txt"));
            
            for (int i = 0; i < manager.teams.length; i++)
            {
                Scanner scan = new Scanner(new File("Round32.txt"));
                while (scan.hasNextLine())
                {
                    if (manager.teams[i].getTeamName().equals(scan.nextLine()))
                    {
                        manager.teams[i].setRound64Winner(true);
                    }
                }
                if (!manager.teams[i].isRound64Winner() == true)
                {
                    manager.teams[i].setRound64Winner(false);
                }
            }
            
//            for (int i = 0; i < manager.teams.length; i++)                      // debugging error where only Virginia was stored as a winner
//            {
//                if (manager.teams[i].isRound64Winner() == true)
//                {
//                    System.out.println(manager.teams[i].getTeamName());
//                }
//            }
            
            for (int i = 0; i < manager.teams.length; i++)
            {
                if (manager.teams[i].isRound64Winner() == true && i < 16)
                {
                    textArea1.setText(textArea1.getText() + "#" + manager.teams[i].getTeamSeed() + " " + manager.teams[i].getTeamName() + 
                            " beat #" + manager.teams[15-i].getTeamSeed() + " " + manager.teams[15-i].getTeamName() + "\n");
                }
                else if (manager.teams[i].isRound64Winner() == true && i < 32)
                {
                    textArea1.setText(textArea1.getText() + "#" + manager.teams[i].getTeamSeed() + " " + manager.teams[i].getTeamName() + 
                            " beat #" + manager.teams[(31-i)+16].getTeamSeed() + " " +manager.teams[31-i+16].getTeamName() + "\n");
                }
                else if (manager.teams[i].isRound64Winner() == true && i < 48)
                {
                    textArea2.setText(textArea2.getText() + "#" + manager.teams[i].getTeamSeed() + " " + manager.teams[i].getTeamName() + 
                            " beat #" + manager.teams[47-i+32].getTeamSeed() + " " + manager.teams[47-i+32].getTeamName() + "\n");
                }
                else if (manager.teams[i].isRound64Winner() == true && i < 64)
                {
                    textArea2.setText(textArea2.getText() + "#" + manager.teams[i].getTeamSeed() + " " + manager.teams[i].getTeamName() + 
                            " beat #" + manager.teams[63-i+48].getTeamSeed() + " " + manager.teams[63-i+48].getTeamName() + "\n");
                }
            }
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(GameResults.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GameResults.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_round64ButtonActionPerformed

    private void round32ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_round32ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_round32ButtonActionPerformed

    private void sweet16ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sweet16ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sweet16ButtonActionPerformed

    private void elite8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elite8ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elite8ButtonActionPerformed

    private void final4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final4ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_final4ButtonActionPerformed

    private void finalGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameResults dialog = new GameResults(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animalHumanoidButton;
    private javax.swing.JButton bracketUpsetsButton;
    private javax.swing.JButton elite8Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton final4Button;
    private javax.swing.JButton finalGameButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton northSouthButton;
    private javax.swing.JButton round32Button;
    private javax.swing.JButton round64Button;
    private javax.swing.JTextField roundHeading;
    private javax.swing.JButton sizeTuitionButton;
    private javax.swing.JButton sweet16Button;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    private javax.swing.JButton winsBySeedButton;
    // End of variables declaration//GEN-END:variables

    private Readable newFile(String round64Loserstxt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
